export const ETHNICITY_OPTIONS = [
  {
    value: 'White',
    label: 'White',
    description: 'Origins in Europe, the Middle East, or North Africa.',
  },
  {
    value: 'Black or African American',
    label: 'Black or African American',
    description: 'Origins in the Black racial groups of Africa; includes identities such as Haitian.',
  },
  {
    value: 'American Indian or Alaska Native',
    label: 'American Indian or Alaska Native',
    description: 'Origins in the original peoples of North or South America, including Central America.',
  },
  {
    value: 'Asian',
    label: 'Asian',
    description: 'Origins in the Far East, Southeast Asia, or the Indian subcontinent.',
  },
  {
    value: 'Native Hawaiian or Other Pacific Islander',
    label: 'Native Hawaiian or Other Pacific Islander',
    description: 'Origins in Hawaii, Guam, Samoa, or other Pacific Islands.',
  },
];

export const MEDICAL_HISTORY_GROUPS = [
  {
    title: 'Past or Present Medical History',
    options: [
      'Alcohol or drug problem',
      'Anemia',
      'Anxiety',
      'Arthritis',
      'Asthma',
      'Atrial fibrillation',
      'Dementia',
      'Diabetes',
      'Cancer',
      'Abnormal pap test',
      'Emphysema/COPD',
      'Heart attack',
      'Coronary artery disease',
      'Heart failure / CHF',
      'High blood pressure',
      'High cholesterol',
      'Hypothyroidism',
      'Hyperthyroidism',
      'Kidney disease',
      'Liver disease',
      'Blood clots',
      'Osteoporosis',
      'Peripheral artery disease',
      'Prostate problem',
      'Neuropathy',
      'Sleep apnea',
      'Heart murmur',
      'Migraines',
      'Hepatitis',
      'Diverticulosis',
      'Colon polyps',
      'Positive TB test',
      'Psychiatric depression',
      'Other psychiatric disorder',
      'Seizure disorder',
      'Stroke',
      'Stomach ulcers',
      'STD or sexual infection',
    ],
  },
  {
    title: 'Surgeries',
    options: [
      'Appendectomy',
      'Tonsillectomy',
      'C-section',
      'Cardiac bypass (CABG)',
      'Hernia repair',
      'Hysterectomy, partial',
      'Cardiac angioplasty/stent',
      'Prostate surgery',
      'Hysterectomy, total',
      'Gallbladder laparoscopic',
      'Vasectomy',
      'Tubal ligation',
      'Gallbladder open',
      'Cataract surgery',
      'Breast surgery',
      'Orthopedic surgery',
      'Other surgery',
    ],
  },
  {
    title: 'Substance Use',
    options: [
      'Alcohol use',
      'Tobacco use',
      'Cannabis use',
      'Opioid use',
      'Stimulant use',
      'Sedative use',
      'Hallucinogen use',
      'IV drug use',
    ],
  },
];
